version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: weave-demo-server:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      # Tip: if you start using Postgres in dev, add DATABASE_URL here too.
      # - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"

  client:
    image: node:20-alpine
    working_dir: /client
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
    depends_on:
      - server

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - server
    command: tunnel --protocol http2 --no-autoupdate --url http://server:${PORT}
